### ISSUE TITLE
Adding html objects into Jodit editor

### ISSUE THREAD

**Issue by ghost** [xdan/jodit#130]
Hey, 
I would like to ask if there is any example of adding html (tables) by using shortcuts into Jodit editor.
For example, one shortcut for control is generated and into dom is loaded hidden html for the table which needs to be added to the editor. 

It looks like this : 

this is shortcut for the table: 

[Details] and into hidden object : <table><tr><td> this needs to be loaded when [Details] is dropped into jodit</td> </tr> </table>

Thank you in advance for your help!

**Comment by modnar1226** [comment]
I feel like I want some answers on this subject too although I'm not sure i fully understand the original request.
Jodit version 3.1
linux mint18
firefox version 65 64-bit

I'm trying to add pre-written html to the edit area defined by class .jodit_wysiwyg 
I'm using jquery, response.post is a variable containing html from a database.
I can confirm the html is present because I am also adding it to a preview area and that shows the html correctly.
My jquery code:
```
var wysiwyg = $(document).find('.jodit_wysiwyg');
wysiwyg.html(response.post);
```

I do not get any new content in the mentioned div. Is this possible to do, or am I not doing it right?
Any help would be appreciated.

**Comment by elshobokshy** [comment]
I'm wondering the same thing.

**Comment by xdan** [comment]
Hi
```html
<textarea id="herewillbeeditor"></textarea>
```
```javascript
window.joditEditor = new Jodit('#herewillbeeditor');
```
Somewhere in your code
```javascript
var wysiwyg = Jodit.instances['herewillbeeditor'];
wysiwyg.value = response.post;
// or 
window.joditEditor.value =  response.post;
```

**Comment by elshobokshy** [comment]
@xdan personally when I try to add HTML (that came encoded through an HTML database) and try to parse it into Jodit ...
```
editor.value(content);
```
... it parses the encoding as is and doesn't decode. Any idea why?

```
var editor = new Jodit('#jodit');
editor.value = '%0D%0A%3Ctable+style%3D%22width%3A+100%25%3B%22%3E%3Ctbody //...etc';
```

**Comment by xdan** [comment]
Jodit does not decode your data. Decode data and paste in Jodit
```js
var editor = new Jodit('#jodit');
const html = someDecoder(''%0D%0A%3Ctable+style%3D%22width%3A+100%25%3B%22%3E%3Ctbody ');
editor.value = html;
```

**Comment by xdan** [comment]
decodeURIComponent('%0D%0A%3Ctable+style%3D%22width%3A+100%25%3B%22%3E%3Ctbody')
I think it will be work for your data

**Comment by elshobokshy** [comment]
@xdan thanks a lot, it worked! :D
