### ISSUE TITLE
ASP.NET Uploader

### ISSUE THREAD

**Issue by ghost** [xdan/jodit#133]
Hi Everyone.

I'm trying to put imagem load on editor, but its not load for me.

I'm using ASP .Net MVC 4.

What its wrong ?

Jodit Version:  3.1.92

```
var editor = new Jodit('#editor', {
    buttons: ['image'],
    uploader: {
        url: '/Editor/UploadFiles',
        process: function (resp) {
                 return {
                     files: resp.files || [],
                     path: resp.path,
                     baseurl: resp.baseurl,
                     error: resp.error,
                     msg: resp.msg
                 };
            },
        defaultHandlerSuccess:function(data,rep){
            var i, field = 'files';
            if (data[field] && data[field].length) {
               for (i = 0; i < data[field].length; i += 1) {
                   this.selection.insertImage(data.baseurl + data[field][i]);
               }
            }
     },

    },
});
```

**Comment by dfreerksen** [comment]
It's difficult to say what the problem is without more information. Your `process` method looks like it's from an example from Jodit v2 documentation.

I just went through the same problem but with Ruby instead of .Net. In my case, the big problem was the format of the JSON response. I suspect it's a similar issue for you.

In my case, all I had to do was specify the URL for the uploader like this

```
var editor = new Jodit('#editor', {
  ...
  uploader: {
    url: '/Editor/UploadFiles'
  },
  ...
});
```

The JSON response needed to be in the following format

```
{
  "success": true,
  "time": "2019-03-29 00:00:00",
  "data": {
    "baseurl": "https://foo.bar/",
    "path": "",
    "files": [
      "image.jpg"
    ],
    "messages": []
  }
}
``` 

I have "files" and "messages" as an array. It should also accept a string.

From there, Jodit did all of its own work and I didn't need to customize or override any methods.

I hope this helps.
