### ISSUE TITLE
Unexpected behavior formatting selected text

### ISSUE THREAD

**Issue by leonardo-avila** [xdan/jodit#189]
**Jodit Version:**  3.2.36

**Problem**

When I select a part of the text and try to apply some formats, like center text or change font style, the editor applies the changes to all content after my selection (even though the text is not selected). I tested this issue selecting the first three bullets in the editor on Jodit's website. After selection, I tried to centralize the text and the result was: the selected and following text centralized, different from the expected result, that should be only the selected text centralized. This issue occurs with many different types of formatation. I think it could be something in selection behavior.

**Expected behavior:**

Only selected text formatted.

**Actual behavior:**

Selected and following text formatted.

**Comment by MachinisteWeb** [comment]
Hello @xdan and Jodit Team!

I'm facing the same problem.

**Jodit Version:** 3.2.44

**Expected behavior:**

1. When we select one block, block style should be applied only to the block selected ![image](https://user-images.githubusercontent.com/3882169/57144792-24ccdf00-6dc2-11e9-86ef-30d95fc2279b.png)

2 . When we select entirely multiple blocks, block style should be applied on all selected block ![image](https://user-images.githubusercontent.com/3882169/57144961-868d4900-6dc2-11e9-9200-efea1b25d00e.png)

3. When we select partially multiple blocks, block style should be applied for all content into selected blocks ![image](https://user-images.githubusercontent.com/3882169/57145119-d0762f00-6dc2-11e9-8dcf-44db6c18d4ef.png)


**Observed behavior:**

1. Do what we expeted

2. All blocks selected are stylized but also all blocks above, that is not correct.
![image](https://user-images.githubusercontent.com/3882169/57145298-3a8ed400-6dc3-11e9-9cc1-b3c83cc92550.png)

3. All blocks partially selected are stylized but also all blocks above, that is not correct. 
![image](https://user-images.githubusercontent.com/3882169/57145466-8f324f00-6dc3-11e9-8d11-db28875bdede.png)


**Additional behavior:**

If we first use a bold or italic change (an inline change), after, the feature work as expected! 
![image](https://user-images.githubusercontent.com/3882169/57145924-7d04e080-6dc4-11e9-9512-2bea3b62ba42.png)
