### ISSUE TITLE
Features fail after build

### ISSUE THREAD

**Issue by amrita-syn** [xdan/jodit#225]
**Jodit Version:**  3.1.xxxxx

Using Jodit as part of a react application with Jodit in its own component. However, when I build the app and serve from the build directory on Apache server, the editor has numerous issues. E.g. the right tool is not highlighted for bold/italic/underline content, changing text size fails, etc.

**Expected behavior:**
Should perform as expected when app is built as a static site.
**Actual behavior:**
After build process, features fail to work as expected.

Check deployed editor - https://amrita-syn.github.io/react-jodit/

**Comment by amrita-syn** [comment]
Any update on this? Proxying and running front-end as an application(my temporary solution to using jodit in the app) is inefficient.

**Comment by amrita-syn** [comment]
My workaround was to add it as a script tag in `public/index.html`. 
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jodit/3.2.55/jodit.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/jodit/3.2.55/jodit.min.js"></script>
```
And then use in components like so -
```
const Jodit = window.Jodit;
const editor = new Jodit('#editor');
```
Doesn't actually solve the build problem but minified here or there - has the same result altogether.

**Comment by vladimyr** [comment]
This happens due to following line of code: https://github.com/xdan/jodit/blob/3.2.55/src/modules/helpers/checker/isJoditObject.ts#L18

Once you compile your bundle in production mode Jodit gets processed by uglify/terser resulting in function names being mangled. `jodit.constructor.name` becomes random id instead of expected string `Jodit`. Some of editor functions (failing ones) use given check as precondition resulting in those features failing silently. And that is just one of the reasons why checking constructor name is considered an antipattern ⚠️  

In order to temporarily circumvent it you can add following line of code to your codebase (before you create first Jodit instance):
```js
Object.defineProperty(Jodit, 'name', { value: 'Jodit' });
```
That essentially overwrites Jodit's constructor `name` to match expected value.
