### ISSUE TITLE
Am i the only one struggling with the image/upload?

### ISSUE THREAD

**Issue by screechyboy79** [xdan/jodit#25]
Love the WYSIWYG however naturally I dont want to upload my images to your webserver and am finding the documentation confusion... where can i change the settings for this so that it uploads new images to my server and it browses my own webserver for already uploaded images?

**Comment by xdan** [comment]
You need connector on your server. https://github.com/xdan/jodit-connectors

**Comment by dannystyleart** [comment]
Hello @xdan,
I have opened a similar issue #31 .
Is this sure that there should be no option to customize the way of upload? 

Like it would be fine to just make an option to pass a function that gets the selected files as an argument and a reject/resolve params

the resolve must get an src that can be used for images and the error could get any object that is passed to handleError.

**Comment by xdan** [comment]
Hi, in last example i tried show how change default sender https://xdsoft.net/jodit/doc/types/UploaderOptions/

**Comment by dannystyleart** [comment]
@xdan 
Just seen, that the documentation was updated. At the moment I have no chance to make a test drive but noticed, that I have forgot what I need to achieve:

I have to send the upload request in the following format:

CORS request to a json REST API with POST method with the following request payload:

`{
   type: 'entity-name',
   attributes:{
      image: 'data:base64/jpeg.......'
   }
}`

Currently I can't receive the selected files to read in and convert to base64.

Is there any plan to get it?

**Comment by xdan** [comment]
In 3.1.77 `buildData` can return Promise
https://xdsoft.net/jodit/doc/types/UploaderOptions/
But i think it works not in all browsers. i checked in last Firefox and last Chrome

**Comment by dannystyleart** [comment]
@xdan I have tried that example and hell yeah, it works!
One thing that I could not really understand but now its clear:
In the Ajax.ts I have found that when the ajax request is done you match the status code only via 200 ( success ). This makes a false positive error because we are getting 201 ( created ) response from backend so this success code should be configurable or a range of 20x status codes that are originally all meant to be code for successful responses.

Should I make a PR on that?

**Comment by xdan** [comment]
I will be very grateful to you

**Comment by dannystyleart** [comment]
@xdan I have made the commit but I can't push to the repo, neither create a PR.
Could you grant permisisons?

**Comment by xdan** [comment]
You need create fork, https://c2n.me/3TaghB6, clone it and make some branch
`git checkout -b ajax_feature`
 after you fixes do commit and pull this branch to your forked repository, after this when you will sign in your account you will see Pull Request button above your fork.

**Comment by IvanBarbaric992** [comment]
Hello @xdan, I have a problem, working in react-redux and .net core. I have a file sistem in .net core which is able to take id parameter and list of files send from react side. In these case files are images from jodit. 

` public class Request
        {
            public int Id { get; set; }
            [Required]
            public List<IFormFile> Files{ get; set; }
        }`
This is request in core, and it works with postman without any problem, when I try upload image/images from jodit editor it binds id but files are not binded. Can you please help me out because I can not find the solution. This is my code from uploader: 
`uploader: {

            url: `somepath`,
            // insertImageAsBase64URI: false,
            imagesExtensions: ["jpg", "png", "jpeg", "gif"],
            // withCredentials: true,
            filesVariableName: function (e) {
              return "Files";
            },

            headers: {
              Authorization:
                "bearer token",
            },

            prepareData: function (data) {
              data.append("id", 16);
              console.log(data);
              return data;
            },

            isSuccess: function (resp) {
              return resp;
            },
            process: function (resp) {
              return {
                files: resp.files,
                path: resp.path,
                baseurl: resp.baseurl,
                error: resp.error,
                message: resp.message,
              };
            },

            defaultHandlerSuccess: function (data) {
              var i,
                field = "files";
              if (data[field] && data[field].length) {
                for (i = 0; i < data[field].length; i += 1) {
                  this.selection.insertImage(data.baseurl + data[field][i]);
                }
              }
            },
          },`
Thank you in advance.
