### ISSUE TITLE
Editor not respecting paste as HTML option when setting askBeforePaste option to false

### ISSUE THREAD

**Issue by Exponent500** [xdan/jodit#276]
**Jodit React version:**  1.0.26

**Browser:**  Chrome
**OS:**  Mac

**Code**

Here is the config option I am passing:

```js
{
        readonly: false,
        showCharsCounter: false,
        showWordsCounter: false,
        showXPathInStatusbar: false,
        buttons: "bold,italic,underline,ol,ul,link, table, align, brush",
        buttonsMD: "bold,italic,underline,ol,ul,link, table, align, brush",
        buttonsSM: "bold,italic,underline,ol,ul,link, table, align, brush",
        buttonsXS: "bold,italic,underline,ol,ul,link, table, align, brush",
        placeholder: "Type your message",
        askBeforePasteFromWord: false,
        askBeforePasteHTML: false
      }
```

**Expected behavior:**

Given that I have not explicitly set the defaultActionOnPaste property within the config option object above, I would expect anything pasted would be pasted as un-cleared HTML.

**Actual behavior:**

Whatever I am pasting is being pasted as cleared HTML. This even occurs when playing with the jodit playground.

**Comment by xdan** [comment]
https://xdsoft.net/jodit/play.html?askBeforePasteHTML=false&askBeforePasteFromWord=false&defaultActionOnPaste=insert_clear_html&currentTab=State

It works properly

**Comment by StukalovSS** [comment]
I have the same problem in v3.3.10.
My config look like this:
`...
askBeforePasteFromWord: false,
askBeforePasteHTML :  false,
defaultActionOnPaste: "insert_as_html",
...`

Link to the playground wits configs: https://xdsoft.net/jodit/play.html?uploader%5BinsertImageAsBase64URI%5D=true&askBeforePasteHTML=false&askBeforePasteFromWord=false&currentTab=State. For example you can paste text from this file: https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0/edit#

When I paste text from Word (or another word processor), the text look like if I used param "INSERT_CLEAR_HTML", but when I do this with the "askBeforePasteFromWord": true parametr, Jodit correctly keeps the text format. In issue #240 this problem was solved by disabling the "paste" plugin, but in this case, the insertion of images from buffer does not work. 

UPD: this problem is actual only for browsers based on Chromium
