### ISSUE TITLE
IE11: pasting simple text is broken

### ISSUE THREAD

**Issue by corrrso** [xdan/jodit#340]
Jodit Version:  3.3.22

Browser:  Internet Explorer 11
OS:  Windows

You can replicate this on jodit Playground.

Simply, if I paste any content, this content goes up to the top of the editor.

Before:
![image](https://user-images.githubusercontent.com/23524581/74346285-a4ef8e80-4daf-11ea-8b4f-1d977a007ef7.png)

After:
![image](https://user-images.githubusercontent.com/23524581/74346317-b46ed780-4daf-11ea-8d45-5094e75e43a0.png)

the same thing happens with links and other stuff:

![image](https://user-images.githubusercontent.com/23524581/74346412-d9fbe100-4daf-11ea-99b4-68bf837e6276.png)

this is quite a big one...

**Comment by xdan** [comment]
@corrrso Is it bug only in Jodit React?

**Comment by corrrso** [comment]
@xdan no it's not. The only library I use is JQuery. Anyway, I saw that you released a new version. Let me try that first.

Edit: I'm afraid that still happens even with 3.3.23

**Comment by xdan** [comment]
@corrrso But here https://xdsoft.net/jodit/ there is not this bug ?

**Comment by corrrso** [comment]
@xdan Acually you are right. at https://xdsoft.net/jodit/ I can't replicate it.

Anyway, I can replicate it with ease at https://xdsoft.net/jodit/play.html without even deleting the default text. And that's the same thing that happens in my environment

![image](https://user-images.githubusercontent.com/23524581/74415837-65bf4d00-4e44-11ea-8db4-8f8941216adb.png)

**Comment by corrrso** [comment]
hi @xdan . I tried to edit the javascript code to help you and what I implemented seems to work. I will make a pull request ASAP.

**Comment by HondzaB** [comment]
The same is in firefox when enabling Insert image as Base64 URI.
https://xdsoft.net/jodit/play.html?uploader%5BinsertImageAsBase64URI%5D=true

**Comment by antonioh** [comment]
It occurs the same in firefox at https://xdsoft.net/jodit/ 

Pasting simple text with Ctrl+V inserts it at the beginning instead of current cursor position.
This is happening in:
    Firefox 76.0.1 (64 bit)
    Windows 10

I attach a gif with the problem at the demo page: (https://xdsoft.net/jodit/) where it can be seen how I:
1. Select text from the Editor
2. Position cursor on the next line
3. Press Ctrl+V and text is inserted at the very top instead of cursor position
4. Repeat copy, position cursor on nexte line and Ctrl+V -> Text is inserted again at the very top

![joditEditor-paste](https://user-images.githubusercontent.com/722865/82438137-dbb4ff00-9a98-11ea-97a2-1503428071ac.gif)
