### ISSUE TITLE
beforePaste and processPaste not firing first paste

### ISSUE THREAD

**Issue by muriloSanto** [xdan/jodit#342]
**Jodit Version:** 3.3.23

**Browser:** chrome/FF
**OS:**  Windows/Mac

**Code**
```js
this.editor = new Jodit(`#${this.id}`, {
      showCharsCounter: false,
      showWordsCounter: false,
      askBeforePasteHTML: false,
      askBeforePasteFromWord: false,
      defaultActionOnPaste: 'insert_as_html',
      tabIndex: 0
    });

    this.editor.events.on('beforePaste', (event) => {
      const target = event.clipboardData || window.clipboardData || event.originalEvent.clipboardData;
      const pastedText = target.getData('text/plain') || target.getData('text/html');
      console.log("beforePaste");
      if (pastedText.indexOf('data:image') !== -1 || pastedText.indexOf('src="data:image"') !== -1 || pastedText.indexOf('base64') !== -1) {
        return false;
      }
    });

    this.editor.events.off('processPaste.paste').on('processPaste.paste', (event, text, type) => {
      if (text && /.*\<img.*src=".*base64.*[\S\n\r\s]*">.*/g.test(text)) {
        return text.replace(/\<img.*src=".*base64.*[\S\n\r\s]*">/g, '');
      } else {
        return text;
      }
    })
```

**Expected behavior:**
Every paste should get processed and remove all IMG with base64 src. Not even the console.log.

**Actual behavior:**
on first paste does not fires any of these events.

**Comment by muriloSanto** [comment]
Looking at the source we've found what seems to be a problem:

on line 485 from paste.ts there is a condition that checks first original beforePaste method and then our own. BUT, on the original beforePaste you execute the pasting, and returns false on insertHTML (to avoid duplicity). 

Should the beforePaste insert any content? 
If you do you'll never get to the point to check processPaste. 

In 485 changing the order from the verification get my custom beforePaste event running, but never the processPaste.

**Comment by muriloSanto** [comment]
Not fixed.

Continues not to fire on first beforePaste and does not executes processPaste.

**Comment by muriloSanto** [comment]
up
:(

**Comment by tomipaul** [comment]
Hey, I'm also experiencing this issue. My code is similar to that of muriloSanto. I'm attempting to sanitize some html input on paste.

I did some digging - On the first paste, the input is not yet in the buffer so the beforePaste runs, returns false and cancels the progression. Subsequently, the input is in the buffer so the beforePaste terminates early, returns undefined and the progression continues (albeit missing the processPaste because of the buffer).

By setting `processPasteHTML` to false, I'm able to bypass the issue for inputs interpreted as `text/html` but for those interpreted as `text/plain`, there's no way around. These `text/plain` inputs are html tokens by the way - something like `<b>Be bold</b>`. I notice this happens for all _formatting_ tags; `b, i, table` etc.(perhaps all that could be applied within the editor itself)
