### ISSUE TITLE
Insert Link trigger change event's value without href and content text

### ISSUE THREAD

**Issue by iamdhj** [xdan/jodit#384]
**Jodit Version:**  3.3.24

**Browser:**  Chrome
**OS:**  Windows

**Code**

```js
<textarea id="editor"></textarea>
<script>
    const editor = new Jodit('#editor');
    editor.events.on('change', (value ) => console.log(value )) //  after insert link value is "<a></a>"
</script>
```

**Expected behavior:**
Insert Link change event should return complete link text like: `<a href="xxx">xxx</a>`

**Actual behavior:**
Insert Link change event only return `<a></a>`, when focus editor it will trigger change event again and return real link text `<a href="xxx">xxx</a>`

**Comment by xdan** [comment]
Fixed in https://github.com/xdan/jodit/releases/tag/3.4.1

**Comment by pmsferreira** [comment]
I have a similar issue. 
I add a link and the change event return this on logs:

![Screenshot 2020-10-21 at 11 52 34](https://user-images.githubusercontent.com/16557512/96710402-eea76480-1393-11eb-8326-879f371d6333.png)

I notice that this only happens when I try to add a link. 
I have 3.4.29 version installed.
