### ISSUE TITLE
unable to access data from extraButtons. ex: name property

### ISSUE THREAD

**Issue by jyoon006** [xdan/jodit#502]
**Jodit Version:**  3.4.23

**Browser:**   Chrome
**OS:**   Mac

**Code**

```js
// A *self-contained* demonstration of the problem follows...
const config = {
  getIcon: (name) => {
    // name for newButton will never show up here, just as `undefined`
  },
  extraButtons: [{ name: 'newButton' }]
}
```

**Expected behavior:**

extraButtons should have some icon name property that i can define in order to use custom icon.

I just need a way to set a custom icon in the extraButtons without using existing `icon string` or `iconURL`

**Actual behavior:**

no way for me to set custom icon for extraButtons if it's not `icon` or `iconURL`
icon property only accepts existing icons only as well

**Comment by romarioliveira25** [comment]
Same issue here.

**Jodit Version:** 3.4.26

**Comment by xdan** [comment]
Hi, this is correct behavior. An icon for a button can be set only if it is present in the Icon module
If it is not there, the text will be inserted.
You can complete the module yourself
```js
Jodit.modules.Icon.set('newButton', ' '); // eny not empty string
```
And you code will work, but getIcon should be in events

**Comment by jeffs365** [comment]
Hi @xdan, sorry i know this is not the place to post this (jodit-react) but may be you can provide info or workaround?
yesterday i'm using jodit-react@1.0.42 (which is jodit@3.3.24)...
because of the issue regarding paste event not trigger/fire, ive decided to update it to latest version jodit-react@1.0.65 with latest jodit version on it.
and then i encounter this issue getIcon is not able to get name/clearName for both custom buttons and extra buttons.
i dont think i do have access to "modules". any advice? thanks

**Comment by xdan** [comment]
https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3428 Added option for this
