### ISSUE TITLE
Backspace and Delete have an errant character

### ISSUE THREAD

**Issue by miltonh26** [xdan/jodit#597]
When back spacing or deleting characters in a TEXTAREA an extra Â appears that needs to be deleted. This occurs every 3-4 characters and happens on all browsers. 

![image](https://user-images.githubusercontent.com/5038455/103724450-e4961900-5006-11eb-9424-c434062acaa5.png)

**Jodit Version:**  3.5.4

**Browser:**  
Firefox 84.0, Chromium 87.0.4280.88, Chrome Version 87.0.4280.88

**OS:**  
Kubuntu 20.04 (Ubuntu 20.04 base)

**Is React App:**  
False

**Code**

**Expected behavior:**
No extraneous characters be added to text when deleting characters within a TEXTAREA. 

**Actual behavior:**
Extra 'Â' characters are typed by Jodit automatically when deleting characters with the Backspace or Delete keys.

**Comment by cbuff18** [comment]
How do I fix this in javascript ?

**Comment by DevelopmentDan** [comment]
This bug is back in the latest version (Version: v4.2.27) (Chrome Version 129.0.6668.71 (Official Build) (64-bit))

Pressing backspace / delete inserts this character - but you have to be working in whitespace for the issue to happen.

![image](https://github.com/user-attachments/assets/9fe40640-2ab1-4a03-9909-526895a56a9f)
