### ISSUE TITLE
Plugin format-block: use with styles instead of elements / support custom Elements

### ISSUE THREAD

**Issue by ulfw** [xdan/jodit#785]
I want to add to more styles of blocks to the editor. Basically it´s a normal p tag with a style.
As far as I can see I cannot add a style to the "Jodit.controls.paragraph.list" section.
So I added a custom element (extends either p or blockqoute) with styles. But this custom element is always wrapped in p tags.

Is there any way to add styles to the "Jodit.controls.paragraph.list" or how can I disable the behaviour to wrap my custom element in p tags?

**Comment by ulfw** [comment]
After digging into the code the easiest way should be to override the IS_BLOCK constant (ok, then its no a constant anymore) and use custom elements.

**Comment by xdan** [comment]
@ulfw I think the best solution would be to add a setting to the WrapTextNodes plugin

https://github.com/xdan/jodit/blob/master/src/plugins/fix/wrap-text-nodes.ts#L116 here instead of ['hr', 'style']
move it to Control

I can do it on the next release. But if you make your own PR, I will be grateful

Then your code will probably be like this
```js
Jodit.make('#editor', {
     wrapNodes: {
      exclude: ['my-component']
    }
})
```

**Comment by ulfw** [comment]
I made a PR regarding this issue. Please check it, before merging. It is my first time with typescript.

But it does not solve my problem. I need the same behaviour as p oder h[1-6]: if I place the cursor at the beginning or in the middle of a line and select a block type, I want that whole paragraph formatted as selected. I do not want to select the text first.
