### ISSUE TITLE
Why setCursorAfter function insert a fake node?

### ISSUE THREAD

**Issue by zackzergzeng** [xdan/jodit#812]
**Jodit Version:**  3.3.24

**Browser:**  Chrome
**Is React App:**  True

I try to use ```insertNode``` function to insert ```<p>``` element, but always have one invisible element after my insert node like below photo
<img width="134" alt="image" src="https://user-images.githubusercontent.com/42129897/159882145-58597e2a-a5d1-4925-a707-7cd79055410d.png">
I read source code and it show ```setCursorAfter``` function insert fake node
<img width="525" alt="image" src="https://user-images.githubusercontent.com/42129897/159882699-44b8a3d5-292c-412d-946d-56c544319344.png">

so why this function insert fake node? and how can i do to insert a node without invisible element

**Comment by xdan** [comment]
@zackzergzeng Because some browsers handle such a cursor differently.

`<ol><li>test</li></ol>|`

in chrome it will be converted to

`<ol><li>test|</li></ol>`

and in FF it will work as you expect;

Therefore, the editor itself adds a text node.
to determine this behavior.
The method returns a `fakeNode` so you can remove it right away if it doesn't suit you

**Comment by zackzergzeng** [comment]
But insertNode function do not return this fakeNode. So how can I do to remove fakeNode after insertNode?

**Comment by zackzergzeng** [comment]
I use setTimeout and selection.removeNode function to find and remove this fake node.
![image](https://user-images.githubusercontent.com/42129897/160316190-4ca0aa06-f6f0-4c83-8a29-433b90cf317b.png)
